# Generated by Django 6.0.4 on 2026-05-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='memebers',
            new_name='members',
        ),
    ]
