# Generated by Django 6.0.4 on 2026-05-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asigned_to',
            new_name='assigned_to',
        ),
    ]
